# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#   - board: nice_nano
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#

include:
  - board: nice_nano_v2
    shield: hatsu64_dongle_central dongle_display
    artifact-name: hatsu64_dongle_central
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y 
      -DCONFIG_ZMK_STUDIO_LOCKING=n

  - board: nice_nano_v2
    shield: hatsu64_left_central
    artifact-name: hatsu64_left_central
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y 
      -DCONFIG_ZMK_STUDIO_LOCKING=n

  - board: nice_nano_v2
    shield: hatsu64_left_peripheral
    artifact-name: hatsu64_left_peripheral
    cmake-args: >
      -DCONFIG_ZMK_SPLIT=y 
      -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano_v2
    shield: hatsu64_right_peripheral
    artifact-name: hatsu64_right_peripheral
    cmake-args: >
      -DCONFIG_ZMK_SPLIT=y 
      -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano_v2
    shield: settings_reset

  - board: nice_nano_v2
    shield: hatsu64_dongle_central dongle_display
    artifact-name: hatsu64_dongle_central_with_logging
    snippet: zmk-usb-logging
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y 
      -DCONFIG_ZMK_STUDIO_LOCKING=n
    
